### ISSUE TITLE
jar 파일.

### ISSUE THREAD

**Issue by Nineclown** [Nineclown/The-Convenient-ATM#15]
로컬에서 gradle jar 돌리면 
![image](https://user-images.githubusercontent.com/12421277/40568078-5f976b7c-60b3-11e8-9f94-ac7f09eedc8a.png)
이런 에러가 나네요 ㅠ..

![image](https://user-images.githubusercontent.com/12421277/40568095-75f58da4-60b3-11e8-8152-365cde4caaef.png)

여기서 난다고 하는데.. 어떤 문제인지 알 수 있을까요?

그리고 pt할 때 사용하신 jar파일도 압축해서 보내주시면 좋을 꺼 같아요!

**Comment by hyeon1018** [comment]
확인하고 알려드리겠습니다.
일단 jar 파일입니다.
[cppatm+data.zip](https://github.com/Nineclown/The-Convenient-ATM/files/2041268/cppatm.data.zip)

**Comment by hyeon1018** [comment]
#16 의 릴리즈 올라온 파일으로 작동합니다.
