### ISSUE TITLE
Failed test: ATM 지폐 보유량 한도를 초과하는 금액을 입금한다.

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#17]
ATM이 Freeze 상태로 전환되고, 입금 금액만큼 ATM 지폐 보유량이 증가한다.

T162: ATM 지폐 보유량 한도를 초과하는 금액을 입금한다.
https://jaehyun379.testrail.io/index.php?/tests/view/162

**Comment by Nineclown** [comment]
취소.

**Comment by Nineclown** [comment]
삭제되었습니다.
