### ISSUE TITLE
Failed test: 입금 후 계좌의 잔액이 정상적으로 증가하였는지

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#18]
1. 입금 과정에서 계좌번호 및 비밀번호 입력 후, 입금 단계 도중 atm의 지폐 보유량을 변경하고 다시 입금창으로 돌아와 지폐 장수를 입력하면 입금이 되지 않는다. 이 상태에서 입금창의 취소 버튼을 누르면 메인화면이 관리창으로 변한다.

2. atm 지폐 보유량 한도를 초과하는 입금을 시도할 경우 거래가 취소된 후 atm이 잠기며, 시도한 입금만큼 atm 지폐 보유량이 증가한다.

3. 0원 입금이 정상적으로 처리된다.

4. 지폐 입력 단계에서 유효하지 않은 값을 입력한 뒤(ex. 문자열) 입력을 누르면 경고창이 실행되지 않는다.

T195: 입금 후 계좌의 잔액이 정상적으로 증가하였는지
https://jaehyun379.testrail.io/index.php?/tests/view/195

**Comment by hyeon1018** [comment]
2 는 #37 에 해당합니다.

**Comment by zinozzino** [comment]
1. User function을 실행중일때 Admin function을 막고, 반대의 경우도 마찬가지로 하면 해결될 문제. 어차피 현실 ATM에서도 사용자가 작업하는 가운데 갑자기 관리자가 와서 뚜껑을 열어서 돈을 가져가지는 않는다.

2. 해결

3. 양수로 예외처리하겠음.

4. 지폐 입력 단계에서 유효하지 않은 값을 입력한 뒤(ex. 문자열) 입력을 누르면 경고창이 실행되지 않는다. -> JNumberField 생성

**Comment by hyeon1018** [comment]
1. 해결 취소버튼을 누르면 현재 로그인된 관리자를 확인하여 창을 바꾸기 때문에 발생함. 확인 절차를 수정하여 해결함.

**Comment by gkgjsrb** [comment]
테스트 결과 정상적으로 동작함
