### ISSUE TITLE
Failed test: 환율을 받아오는 기능

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#19]
100달러 지폐의 환율이 다른 지폐에 비해 높다

T197: 환율을 받아오는 기능
https://jaehyun379.testrail.io/index.php?/tests/view/197

**Comment by hyeon1018** [comment]
저희 구현은 환율 받아오는 부분과 지폐의 금액을 계산하는 부분이 서로 독립적으로 작동하고 있어서 100달러지폐의 환율만 잘 못 받아올 수 있는 경우가 없다고 생각합니다.
테스트한 결과를 같이 주시면 참고해보겠습니다.

**Comment by Nineclown** [comment]
Failed test: 한글로 적힌 테스트들은 특정 조건을 정해놓지 않고 막 테스팅하는 거라
pass인 것 같네요. 죄송합니다. closes 하시면 될 것 같아요.

**Comment by gkgjsrb** [comment]
저희가 테스트를 잘못한 부분입니다.
죄송합니다.
