### ISSUE TITLE
Failed test: User가 입력한 금액을 환율에 맞게 계산하여 계좌에 입금하는 기능

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#20]
지폐의 환율이 비정상적으로 높다

T198: User가 입력한 금액을 환율에 맞게 계산하여 계좌에 입금하는 기능
https://jaehyun379.testrail.io/index.php?/tests/view/198

**Comment by hyeon1018** [comment]
#19 ?

**Comment by gkgjsrb** [comment]
저희가 테스트를 잘못한 부분입니다.
죄송합니다.
