### ISSUE TITLE
Failed test: 출금 후 계좌의 잔액이 정상적으로 감소하였는지

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#22]
1. 출금 과정에서 계좌번호 및 비밀번호 입력 후, 출금액 입력창에 상태에서 atm의 지폐 보유량을 출금액보다 적게 변경하고 출금을 시도할 경우, 별도의 거리실패 팝업 없이 메인화면으로 이동한다.

2. atm 보유 지폐량보다 많은 금액의 출금을 시도할 경우 atm 지폐 보유량 및 잔액은 해당 금액만큼 감소하나 거래가 진행되지 않고 atm이 freeze된다.

3. 0원 출금이 정상적으로 처리되며 수수료가 부가된다.

4. 1회 인출 한도가 문서에 명시되어 있지 않다.

T201: 출금 후 계좌의 잔액이 정상적으로 감소하였는지
https://jaehyun379.testrail.io/index.php?/tests/view/201

**Comment by hyeon1018** [comment]
2 는 #37 에 해당합니다.

**Comment by gkgjsrb** [comment]
테스트 결과 정상적으로 동작함
