### ISSUE TITLE
Failed test: 환율을 받아오는 기능

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#23]
100달러 지폐의 환율이 비정상적으로 높다

T204: 환율을 받아오는 기능
https://jaehyun379.testrail.io/index.php?/tests/view/204

**Comment by hyeon1018** [comment]
#19 와 내용이 같고 테스트번호만 다릅니다.
삭제되거나 추가 설명이 필요합니다.

**Comment by gkgjsrb** [comment]
1000에서 작성하신 test case에 deposit foreign cash를 보시면
환율이 제대로 적용되지 않아 1.user가 입력한 금액이 환율에 맞게 계산되지도 않는 경우와
2.계좌의 잔액이 정상적으로 증가하지 않는 경우 둘 다 해당된다고 생각되서 두개를 넣었습니다.
지금 생각해보니 1번만 해당되고 2번은 그 결과로 오류가 생기는 것이기 때문에. close하셔도 될거 같습니다. 새벽에 정신없이 추가해서 죄송합니다.

**Comment by gkgjsrb** [comment]
저희가 테스트를 잘못한 부분입니다.
죄송합니다.
