### ISSUE TITLE
Failed test: User가 출금하려는 금액을 환율에 맞게 계산하여 계좌에서 출금하는 기능

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#24]
100달러 지폐의 환율이 비정상적으로 높다.

T205: User가 출금하려는 금액을 환율에 맞게 계산하여 계좌에서 출금하는 기능
https://jaehyun379.testrail.io/index.php?/tests/view/205

**Comment by hyeon1018** [comment]
#19 로인하여 발생하는 문제로 보이는데 맞나요?

**Comment by Nineclown** [comment]
네 맞습니다!

**Comment by gkgjsrb** [comment]
저희가 테스트를 잘못한 부분입니다.
죄송합니다.
