### ISSUE TITLE
Failed test: 출금 후 계좌의 잔액이 정상적으로 감소하였는지

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#25]
100달러 지폐의 환율이 비정상적으로 높아 100달러 인출후 잔액에 이상이 생긴다

T206: 출금 후 계좌의 잔액이 정상적으로 감소하였는지
https://jaehyun379.testrail.io/index.php?/tests/view/206

**Comment by hyeon1018** [comment]
#19 로인하여 발생하는 문제로 보이는데 맞나요?

**Comment by Nineclown** [comment]
네 맞습니다!. 모두 close 하셔도 될 꺼 같네요!

**Comment by gkgjsrb** [comment]
저희가 테스트를 잘못한 부분입니다.
죄송합니다.
