### ISSUE TITLE
Definition: User가 선택한 조회 기간에 해당하는 거래 내역을 출력하는 기능

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#26]
날짜의 기준이 00시임을 문서에 표시하여야 한다.
(5월 27일을 입력하면 00시 00분인지 23시 59분를 알 수 있어야한다.)

T214: User가 선택한 조회 기간에 해당하는 거래 내역을 출력하는 기능
https://jaehyun379.testrail.io/index.php?/tests/view/214

**Comment by gkgjsrb** [comment]
저희의 생각은 예를들어 5월23부터 5월 28일까지 조회를 하면 5월 23일 00시 00분부터 5월 28일 23시 59분까지 조회하는 것이 맞다고 생각합니다. 시중에 있는 대부분의 은행들도 이런식으로 조회가 가능한 것으로 알고 있습니다.
![image](https://user-images.githubusercontent.com/37429503/40827514-be0997b6-65b8-11e8-9bd7-2aa4b8173912.png)
그리고 이걸 00시까지라고 문서에 명세하다고 해도 사람들이 익숙한 개념과 다르기때문에 c++이라는 컨셉에 맞지 않는다고 생각합니다.
그리고 추가적인 사항으로는 시작날짜와 끝 날짜를 같게한다면
당일 00시00분 부터 23시59분까지를 조회하는게 c++라는 의미에 부합한다고 생각합니다.

**Comment by hyeon1018** [comment]
저희도 그렇게 조회되는게 맞다고 생각하고, 시간을 언급을 안하는 이유는 날짜의 의미가 해당 날짜의 00시00분부터 23시 59분 까지의 모든 시간을 포함하는 개념으로 생각하고 있기 때문입니다.
 
처음 보내드렸을 때는 어땟는지 모르겠지만, 현재는 그러한 방식으로 작동중입니다.
GUI에서 입력받으면서 값을 조정해서 ATMSystem만으로 작동시키면 확인이 안될수 있습니다.

**Comment by gkgjsrb** [comment]
그럼 2018 05 31 12:00:00AM에 거래 내역이 있을 때
시작날짜 : 20180531
끝날짜: 20180531
이렇게하면 조회가 되야 한다고 생각하는데
안나와서
시작날짜 : 20180528
끝날짜 : 20180530
로 입력했는데 여기도 안나오네요.
둘 중에 하나의 경우에는 위 거래 내역이 나와야 하지 않을까요?

**Comment by hyeon1018** [comment]
네 그경계선은 실수로 빠져있어서 조금전에 수정했습니다.

**Comment by gkgjsrb** [comment]
넵 감사합니다!
