### ISSUE TITLE
Failed test: User가 입력한 로또 용지의 숫자를 읽는 기능

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#28]
1.0주차를 정상적인 주차로 인식한다.

2.로또 번호 0을 정상적인 번호로 인식한다.

3.현재 존재하지 않는 주차를 입력해도 정상 인식한다.

T222: User가 입력한 로또 용지의 숫자를 읽는 기능
https://jaehyun379.testrail.io/index.php?/tests/view/222

**Comment by hyeon1018** [comment]
관련 문제들 수정했습니다.
