### ISSUE TITLE
Failed test: 인터페이스의 언어가 전환되는 기능

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#30]
메인화면/관리창에서 각각 언어 변경을 했을 때 다른 창에 즉시 적용되지 않는다.

T228: 인터페이스의 언어가 전환되는 기능
https://jaehyun379.testrail.io/index.php?/tests/view/228

**Comment by zinozzino** [comment]
Main 싱글톤으로 만들고 로케일 변경시마다 초기화면으로 돌리게 바꿨습니다.
