### ISSUE TITLE
Failed test: Admin의 입력에 따라 Admin 계정을 추가하는 기능

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#31]
비밀번호 또는 연락처를 입력하지 않아도 admin 계정이 생성된다.
형식에 맞는 입력에 대한 정확한 정의가 필요하다.
문서상 유효하지 않는 값은 입력 시 초기화면으로 돌아아간도 표기되어 있다.

T229: Admin의 입력에 따라 Admin 계정을 추가하는 기능
https://jaehyun379.testrail.io/index.php?/tests/view/229

**Comment by hyeon1018** [comment]
#52 정의가 이루어진 후 수정합니다.

**Comment by hyeon1018** [comment]
검사하는 과정을 수정하였습니다.
