### ISSUE TITLE
현재 지폐 보유량을 변경하는 기능

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#32]
nonfunctional requirement에 따르면
잘못된 값을 입력하면 유저가 즉각적으로 알 수 있어야 하지만
지폐 보유량에 문자열을 입력하면 경고창이 실행되지 않는다.

T235: 현재 지폐 보유량을 변경하는 기능
https://jaehyun379.testrail.io/index.php?/tests/view/235

**Comment by gkgjsrb** [comment]
테스트 결과 정상적으로 동작함
