### ISSUE TITLE
즉시 언어변경 문제.

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#33]
언어변경하면 즉각적으로 바뀌지 않는다.

T1: 20200
https://jaehyun379.testrail.io/index.php?/tests/view/1

**Comment by hyeon1018** [comment]
#30 과 다른 이슈인가요?

**Comment by Nineclown** [comment]
동일한 이슈 입니다!
test case가 두 개로 나뉜 이유는 하나는 brute force testing에서 나온 case이며, 다른 하나는 CPT testing에서 나온 case라서 그렇습니다.

**Comment by gkgjsrb** [comment]
언어 변경 시 admin이 로그 아웃됨

**Comment by hyeon1018** [comment]
언어변경시 admin이 로그아웃되는 문제는 해결했습니다.
다만 admin 로그아웃 할 수 있는 방법이 없어, 로그아웃버튼을 추가하였습니다.
