### ISSUE TITLE
복권 : 주차 0 입력 에러.

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#35]
복권 주차에 0이나 실제 존재하지 않는 주차를 입력해도
오류로 인식하지 않는다.

T38: 31602
https://jaehyun379.testrail.io/index.php?/tests/view/38

**Comment by hyeon1018** [comment]
#28 2,3

**Comment by gkgjsrb** [comment]
0을 주차로 인식함
![image](https://user-images.githubusercontent.com/37429503/40826979-4dd40d1a-65b7-11e8-9c4c-8169d2a55eb4.png)

**Comment by swp1234** [comment]
![default](https://user-images.githubusercontent.com/7866037/40883165-ddf4f212-6731-11e8-88af-6883df036b6f.PNG)
![123](https://user-images.githubusercontent.com/7866037/40883166-de1bd832-6731-11e8-8de7-b3a32e0a6042.PNG)
두 경우다 제대로 주차를 인식합니다 ㅠㅠ
