### ISSUE TITLE
복권 : 로또번호 0 에러.

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#36]
로또 번호에 0을 입력해도 번호로 인식한다.
(실제 로또번호에는 0이 없음)

T40: 31702
https://jaehyun379.testrail.io/index.php?/tests/view/40

**Comment by hyeon1018** [comment]
#28

**Comment by gkgjsrb** [comment]
여전히 0을 번호로 인식함
![image](https://user-images.githubusercontent.com/37429503/40826923-20c1fef4-65b7-11e8-9dd7-9b438842777f.png)

**Comment by swp1234** [comment]
![default](https://user-images.githubusercontent.com/7866037/40883172-03bd97e2-6732-11e8-8148-b0a70ea10a03.PNG)
수정해서 제대로 동작하는걸 확인하고 커밋한건데 왜 그럴까요?? 위 사진은 지금 레포에 있는 파일 그대로 테스팅 해본것입니다

**Comment by gkgjsrb** [comment]
저희가 test 시작할 때는 release중에 testing start되있는걸로 했어요
혹시 그 때 이후로 수정하신 건가요?

**Comment by hyeon1018** [comment]
네 그 release 다음에 수정된 내용이 몇개 있습니다.
가장 최신 코드 테스트해주실수 있으신가요?

**Comment by gkgjsrb** [comment]
이번 테스트가 dslab에 올라온 소스코드 기준이라, 저희 오늘 발표는 그걸 기준으로 발표하고
수정하셨으니 수정하셨다고 발표하시고 저희가 마지막 발표 때 모델링팀에서 수정했다고 발표할거 같습니다.

**Comment by hyeon1018** [comment]
네 알겠습니다.
