### ISSUE TITLE
언어 변경

### ISSUE THREAD

**Issue by hyeon1018** [Nineclown/The-Convenient-ATM#4]
언어가 아직 변경이 되지 않는 곳이 있음.
찾으면 적어놓기.
혹시 Dialog에 언어변경 할 수 없음?

**Comment by zinozzino** [comment]
## 상황

완료되면 표시해주세요.

- [x] AdminSelectFunction
- [x] AuthorizeAdmin
- [ ] ChangeLocale
- [x] EnterAdminInfo
- [x] EnterBill
- [ ] EnterBillAsDollar
- [ ] EnterDate
- [x] EnterLottery
- [ ] EnterNumber
- [ ] EnterPassword
- [ ] PrintResult
- [ ] QueryATMBalance
- [ ] QueryBalance
- [ ] QueryList
- [ ] RequestCardOrBankbook
- [x] SelectFunction

**Comment by zinozzino** [comment]
그리고 ChangeLocale은 굳이 언어변경할 필요 없이 그냥 둘 다 띄우는게 좋을듯.

**Comment by zinozzino** [comment]
언어변경 완료.
