### ISSUE TITLE
Failed test: 10000.10103.20002.30000.30100.30200.31002.31100.31201.40000.

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#45]
지폐 보유량이 출금이 불가능한 경우(ex. 5만원 1장)일 때
6만원을 인출하면 불가능하다는 오류창이 뜨지만 지폐 보유량과 잔액이 감소한다.(지폐 보유량이 마이너스 값이 됨)
은행이 다른 경우3

T61: 10000.10103.20002.30000.30100.30200.31002.31100.31201.40000.
https://jaehyun379.testrail.io/index.php?/tests/view/61

**Comment by hyeon1018** [comment]
#37

**Comment by gkgjsrb** [comment]
테스트 결과 정상적으로 동작함
