### ISSUE TITLE
거래 내역 조회: 같은 날짜 입력 오류 발생

### ISSUE THREAD

**Issue by jaehyun739** [Nineclown/The-Convenient-ATM#49]
문서에는 시작 날짜보다 작은 날짜를 입력하면 안되다고 나와 있지만
실제로는 시작날짜와 같은 날짜도 오류로 인식한다.

T74: 10000.10104.20006.30000.30100.30200.30800.30902.31000.40002
https://jaehyun379.testrail.io/index.php?/tests/view/74

**Comment by gkgjsrb** [comment]
테스트 결과 정상적으로 동작함
추가적인 사항 : #26
