### ISSUE TITLE
메시지에 대한 명세에 관한 질문입니다.

### ISSUE THREAD

**Issue by gkgjsrb** [Nineclown/The-Convenient-ATM#55]
모델링팀 분들께서 문서에 
'입력 받은 값이 유효하지 않다면 메시지를 띄우고 재입력 받는다 .'
이렇게 표현을 해주셨는데요.
이거에 대해서 모호함이 있는거 같습니다.
계좌번호를 입력할때는 invalid인 경우와 incorrect인 경우에 따라 뜨는 오류창이 다른데
비밀번호를 입력할때는 invalid인 경우와 incorrect인 경우에 따라 뜨는 오류창이 같습니다.
![image](https://user-images.githubusercontent.com/37429503/40828401-75d74d32-65bb-11e8-962d-6d0aaa38249a.png)

**Comment by hyeon1018** [comment]
확인해보니 두개의 메시지가 따른 과정에 의해서 뜨지만, 적합한 메시지를 찾지 못해서 같은 메시지가 들어갔습니다. 언어 수정할 때 같이 수정되었습니다.
