### ISSUE TITLE
Static Analysis: jdepend.

### ISSUE THREAD

**Issue by Nineclown** [Nineclown/The-Convenient-ATM#57]
[jdepend.zip](https://github.com/Nineclown/The-Convenient-ATM/files/2065956/jdepend.zip)

참고용입니다.
패키지 간의 의존성을 분석해주었습니다.

**Comment by gkgjsrb** [comment]
[JDepend.pdf](https://github.com/Nineclown/The-Convenient-ATM/files/2066601/JDepend.pdf)

용어의 의미는 이 ppt에 나와 있습니다.
