### ISSUE TITLE
Static Analysis: code scroll inspector.

### ISSUE THREAD

**Issue by Nineclown** [Nineclown/The-Convenient-ATM#59]
[위배내용.zip](https://github.com/Nineclown/The-Convenient-ATM/files/2065965/default.zip)

code inspector를 통해 발생된 에러일 가능성이 있는 코드들입니다.

**Comment by hyeon1018** [comment]
이러한 코드들 중에서 intllij ui designer에 의해 자동생성된 코드들은 수정하지 않아도 괜찮을까요?

**Comment by Nineclown** [comment]
확인 후에 다시 comment 드리겠습니다.

**Comment by hyeon1018** [comment]
$$$setup$$$() 같은 형식의 메소드들이 자동생성된 코드입니다.
확인하실 때 참고하세요.

**Comment by gkgjsrb** [comment]
방금 조교님께 질문하고 왔는데요.
저희가 판단하는게 아니라고 하셔서 확답을 드릴수가 없네요.
개인적인 의견으로는 자동 생성된 코드는 수정을 하지 않는게 맞는거 같습니다.

**Comment by hyeon1018** [comment]
예 알겠습니다.
