### ISSUE TITLE
계좌 제한상태 

### ISSUE THREAD

**Issue by hyeon1018** [Nineclown/The-Convenient-ATM#7]
계좌 제한상태에서 거래가 처리됨.

**Comment by zinozzino** [comment]
* ui.EnterPassword 에서 ATMSystem.account 의 availability 체크
* ui.RequestCardOrBankbook 에서 ATMSystem.account의 availability 체크

**Comment by zinozzino** [comment]
713528e7d0c077914c3d16ae6b4bd01ffc54f1c7
bf5d2a523039674f2e84dcaeb5be2afd870e8ea1
